\c speak_easy;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS phrases;
DROP TABLE IF EXISTS languages;

CREATE TABLE IF NOT EXISTS languages (
  id BIGSERIAL PRIMARY KEY,
  language VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS phrases (
  id BIGSERIAL PRIMARY KEY,
  phrase VARCHAR(1024),
  language VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(1024),
  password VARCHAR(1024)
);