\c speak_easy;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS phrases;

CREATE TABLE IF NOT EXISTS phrases (
  id BIGSERIAL PRIMARY KEY,
  phrases VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(1024),
  password VARCHAR(1024)
);